apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quotegen.fullname" . }}
  labels:
    {{- include "quotegen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "quotegen.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quotegen.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

