apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "quotegen.fullname" . }}-pre-upgrade-hook
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "quotegen.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "quotegen.fullname" . }}-pre-upgrade-hook
      labels:
        {{- include "quotegen.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: pre-upgrade
        image: curlimages/curl
        command: ['sh', '-c', 'echo The pre-upgrade hook Pod is running && sleep 15']

