apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "quotegen.fullname" . }}-pre-delete-hook
  namespace: {{ .Values.namespace | default "default" }}
  labels:
    {{- include "quotegen.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "quotegen.fullname" . }}-pre-delete-hook
      labels:
        {{- include "quotegen.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: api-test
        image: curlimages/curl
#        command: ['sh', '-c', 'echo The pre-delete hook Pod is running && sleep 60']
        command:
          - "/bin/sh"
          - "-c"
#          - 'curl -s {{ include "quotegen.fullname" . }}:8080/quote'
          - 'echo the pre-delete hook pod is running && sleep 10'
