apiVersion: v1
kind: LimitRange
metadata:
	name: mem-lim-range
spec:
	limits:
	  - default:
		    memory: 512Mi
	    defaultRequest:
		    memory: 256Mi
	    type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
	name: cpu-lim-range
spec:
	limits:
	  - default:
		    cpu: 1
	    defaultRequest:
		    cpu: 0.5
	    type: Container
