apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
  replicas: 3 #for resourcedefinition3.yml
---
apiVersion: "stable.example.com/v1"
kind: CronTab
metadata:
  name: my-new-awesome-cron-object
spec:
  cronSpec: "* * * * */5"
  image: my-awesome-cron-image
  replicas: 3 #for resourcedefinition3.yml