apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pullrequests.stable.liatr.io
  labels:
    app.kubernetes.io/managed-by: helm
spec:
  group: stable.liatr.io
  versions:
    - name: v1
      served: true
      storage: true
  version: v1
  scope: Namespaced
  names:
    plural: pullrequests
    singular: pullrequest
    kind: PullRequest
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required: ["user", "branch", "status",  ”id”]
          properties:
            user:
              type: string
            branch:
              type: string
            status:
              type: string
            id:
              type: string
