apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-vol1
spec:
    accessModes:
      - ReadWriteOnce
    capacity:
        storage: 1Gi
    hostpath:
        path: /tmp/data
    OR
    awsElasticBlockStore:
        volumeID: <volume-id>
        fsType: ext4
              
#kubectl create -f pv-definition.yml
#kubectl get persistentvolume
----
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim