apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: myclaim
spec:
    accessModes:
      - ReadWriteOnce
    resources:
        requests:
            storage: 500Mi

#kubectl create -f pvc-definition.yml
#kubectl get persistentvolumeclaim
#kubectl delete persistentvolumeclaim myclaim

#what happens to underlying PV after PVC is deleted
#persistentVolumeReclaimPolicy: Retain (default) / Delete / Recycle
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: myfrontend
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: mypd
  volumes:
    - name: mypd
      persistentVolumeClaim:
        claimName: myclaim
