apiVersion: apps/v1
kind: ReplicaSet
metadata: 
    name: myapp-replicaset
    labels: #group rs objects
        app: myapp
        type: front-end
    annotations: #to record other information
        buildversion: 1.34
spec: 
    template:
        metadata:
            name: myapp-pod
            labels: #group pod objects
                app: myapp
                type: front-end
        spec:
            containers:
              - name: nginx-controller
                image: nginx
    replicas: 3
    selector: #identify what pods falls under it
        matchLabels:
            type: front-end
    
#kubectl create -f replicaset-definition.yml

#kubectl replace -f replicaset-definition.yml

#kubectl scale --replicas=6 -f replicaset-definition.yml
#kubectl scale --replicas=6 replicaset myapp-replicaset
#but above 2 scale commands will not update yml file


#replicaset can also manage pods not created as part of replicaset definition

