apiVersion: v1
kind: Secret
metadata:
	name: app-secret
data:
#DB_Host: mysql
#DB_Host: root
#DB_Password: paswrd
# to convert plain text to encoded format (hashed format)
#echo -n 'mysql' | base64
#echo -n 'root' | base64
#echo -n 'paswrd' | base64
	DB_Host: bX1zcWw=
	DB_Host: cm9vdA==
    DB_Password: cGFzd3Jk



#kubectl create -f secert-data.yml
#kubectl get secrets
#kubectl describe secrets => but this hides the values
#in order to view the values, run below command
#kubectl get secret app-secret -o yaml => will display hashed values
#below is way to decode hashed values
#echo -n 'bX1zcWw=' | base64 --decode
#echo -n 'cm9vdA==' | base64 --decode
#echo -n 'cGFzd3Jk' | base64 --decode

