apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "simpleton.fullname" . }}-post-upgrade-hook
  labels:
    {{- include "simpleton.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: {{ include "simpleton.fullname" . }}-post-upgrade-hook
      labels:
        {{- include "simpleton.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
      - name: post-upgrade
        image: curlimages/curl
        command: ['sh', '-c', 'echo The post-upgrade hook Pod is running && sleep 15']

